sample_rate = 44100
window_size = 1764
hop_size = 882      # So that there are 64 frames per second
mel_bins = 64
fmin = 50       # Hz
fmax = int(sample_rate/4)    # Hz

frames_per_second = sample_rate // hop_size
audio_duration = 30     # Audio recordings in ESC-50 are all 5 seconds
total_samples = sample_rate * audio_duration
audio_duration_clip = 3
audio_stride_clip = 1
total_frames = frames_per_second * audio_duration
frames_num_clip = int(frames_per_second * audio_duration_clip)
total_samples_clip = int(sample_rate * audio_duration_clip)
frames_num = frames_per_second * audio_duration_clip
audio_num = (audio_duration-audio_duration_clip)//audio_stride_clip + 1
labels = ['babycry', 'None']
classes_num = len(labels)
lb_to_idx = {lb: idx for idx, lb in enumerate(labels)}
idx_to_lb = {idx: lb for idx, lb in enumerate(labels)}
